### ISSUE TITLE
i try to install AUBO Robot and Catkin_make but have Error 

### ISSUE THREAD

**Issue by Tathipan** [auboliuxin/aubo_robot#13]
~/catkin_ws$ rm -rf build/ devel/ && catkin_make
Base path: /home/rase/catkin_ws
Source space: /home/rase/catkin_ws/src
Build space: /home/rase/catkin_ws/build
Devel space: /home/rase/catkin_ws/devel
Install space: /home/rase/catkin_ws/install
####
####
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/rase/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/rase/catkin_ws/devel;/opt/ros/kinetic
-- This workspace overlays: /home/rase/catkin_ws/devel;/opt/ros/kinetic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.12", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/rase/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.12") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.29
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 18 packages in topological order:
-- ~~  - aubo_description
-- ~~  - aubo_e5_moveit_config
-- ~~  - aubo_gazebo
-- ~~  - aubo_i5_moveit_config
-- ~~  - aubo_robot (metapackage)
-- ~~  - tutorial_one
-- ~~  - aubo_demo
-- ~~  - aubo_msgs
-- ~~  - aubo_driver
-- ~~  - aubo_e3_moveit_config
-- ~~  - aubo_i10_moveit_config
-- ~~  - aubo_i16_moveit_config
-- ~~  - aubo_i3_moveit_config
-- ~~  - aubo_i5l_moveit_config
-- ~~  - aubo_i7_moveit_config
-- ~~  - aubo_kinematics
-- ~~  - aubo_controller
-- ~~  - aubo_planner
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'aubo_description'
-- ==> add_subdirectory(aubo_robot/aubo_description)
-- +++ processing catkin package: 'aubo_e5_moveit_config'
-- ==> add_subdirectory(aubo_robot/aubo_e5_moveit_config)
-- +++ processing catkin package: 'aubo_gazebo'
-- ==> add_subdirectory(aubo_robot/aubo_gazebo)
-- +++ processing catkin package: 'aubo_i5_moveit_config'
-- ==> add_subdirectory(aubo_robot/aubo_i5_moveit_config)
-- +++ processing catkin metapackage: 'aubo_robot'
-- ==> add_subdirectory(aubo_robot/aubo_robot)
-- +++ processing catkin package: 'tutorial_one'
-- ==> add_subdirectory(tutorial_one)
-- +++ processing catkin package: 'aubo_demo'
-- ==> add_subdirectory(aubo_robot/aubo_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- <<<<<<<<<<<<<<<<<<<<<<<<<Note: Find Package for kinetic
-- <<<<<<<<<<<<<<<<<<<<<<<<<Note:build aubo_demo node for kinetic
-- +++ processing catkin package: 'aubo_msgs'
-- ==> add_subdirectory(aubo_robot/aubo_msgs)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- aubo_msgs: 6 messages, 4 services
-- +++ processing catkin package: 'aubo_driver'
-- ==> add_subdirectory(aubo_robot/aubo_driver)
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- +++ processing catkin package: 'aubo_e3_moveit_config'
-- ==> add_subdirectory(aubo_robot/aubo_e3_moveit_config)
-- +++ processing catkin package: 'aubo_i10_moveit_config'
-- ==> add_subdirectory(aubo_robot/aubo_i10_moveit_config)
-- +++ processing catkin package: 'aubo_i16_moveit_config'
-- ==> add_subdirectory(aubo_robot/aubo_i16_moveit_config)
-- +++ processing catkin package: 'aubo_i3_moveit_config'
-- ==> add_subdirectory(aubo_robot/aubo_i3_moveit_config)
-- +++ processing catkin package: 'aubo_i5l_moveit_config'
-- ==> add_subdirectory(aubo_robot/aubo_i5l_moveit_config)
-- +++ processing catkin package: 'aubo_i7_moveit_config'
-- ==> add_subdirectory(aubo_robot/aubo_i7_moveit_config)
-- +++ processing catkin package: 'aubo_kinematics'
-- ==> add_subdirectory(aubo_robot/aubo_kinematics)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- <<<<<<<<<<<<<<<<<<<<<<<<<Note: Find Package for kinetic in kinematics build
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:166 (message):
  catkin_package() DEPENDS on 'boost' but neither 'boost_INCLUDE_DIRS' nor
  'boost_LIBRARIES' is defined.
Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  aubo_robot/aubo_kinematics/CMakeLists.txt:16 (catkin_package)

-- +++ processing catkin package: 'aubo_controller'
-- ==> add_subdirectory(aubo_robot/aubo_controller)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   date_time
--   thread
--   chrono
--   atomic
-- +++ processing catkin package: 'aubo_planner'
-- ==> add_subdirectory(aubo_robot/aubo_planner)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   date_time
--   thread
--   chrono
--   atomic
-- <<<<<<<<<<<<<<<<<<<<<<<<<Note: Find Eigen3 Package in aubo_planner for kinetic
-- <<<<<<<<<<<<<<<<<<<<<<<<<Note: Find EIGEN3_INCLUDE_DIRS Package in aubo_planner for kinetic
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rase/catkin_ws/build
####
####
Scanning dependencies of target MoveGroupInterface_To_Kinetic
Scanning dependencies of target Test_Aubokinematic
Scanning dependencies of target _aubo_msgs_generate_messages_check_deps_SetPayload
Scanning dependencies of target AuboTest_kinetic
[  1%] Building CXX object aubo_robot/aubo_demo/CMakeFiles/Test_Aubokinematic.dir/src/AuboTest_kinematic_kinetic.cpp.o
[  2%] Building CXX object aubo_robot/aubo_demo/CMakeFiles/MoveGroupInterface_To_Kinetic.dir/src/MoveGroupInterface_To_Kinetic.cpp.o
[  2%] Built target _aubo_msgs_generate_messages_check_deps_SetPayload
[  3%] Building CXX object aubo_robot/aubo_demo/CMakeFiles/AuboTest_kinetic.dir/src/AuboTest_kinetic.cpp.o
Scanning dependencies of target std_msgs_generate_messages_nodejs
[  3%] Built target std_msgs_generate_messages_nodejs
Scanning dependencies of target _aubo_msgs_generate_messages_check_deps_JointPos
[  3%] Built target _aubo_msgs_generate_messages_check_deps_JointPos
Scanning dependencies of target _aubo_msgs_generate_messages_check_deps_GoalPoint
[  3%] Built target _aubo_msgs_generate_messages_check_deps_GoalPoint
Scanning dependencies of target _aubo_msgs_generate_messages_check_deps_IOState
[  3%] Built target _aubo_msgs_generate_messages_check_deps_IOState
Scanning dependencies of target _aubo_msgs_generate_messages_check_deps_SetIO
[  3%] Built target _aubo_msgs_generate_messages_check_deps_SetIO
Scanning dependencies of target _aubo_msgs_generate_messages_check_deps_Analog
[  3%] Built target _aubo_msgs_generate_messages_check_deps_Analog
Scanning dependencies of target _aubo_msgs_generate_messages_check_deps_Digital
[  3%] Built target _aubo_msgs_generate_messages_check_deps_Digital
Scanning dependencies of target _aubo_msgs_generate_messages_check_deps_TraPoint
[  3%] Built target _aubo_msgs_generate_messages_check_deps_TraPoint
Scanning dependencies of target _aubo_msgs_generate_messages_check_deps_GetFK
[  3%] Built target _aubo_msgs_generate_messages_check_deps_GetFK
Scanning dependencies of target _aubo_msgs_generate_messages_check_deps_GetIK
[  3%] Built target _aubo_msgs_generate_messages_check_deps_GetIK
Scanning dependencies of target std_msgs_generate_messages_py
[  3%] Built target std_msgs_generate_messages_py
Scanning dependencies of target std_msgs_generate_messages_cpp
[  3%] Built target std_msgs_generate_messages_cpp
Scanning dependencies of target std_msgs_generate_messages_eus
[  3%] Built target std_msgs_generate_messages_eus
Scanning dependencies of target std_msgs_generate_messages_lisp
[  3%] Built target std_msgs_generate_messages_lisp
Scanning dependencies of target aubo_gazebo_driver
[  4%] Building CXX object aubo_robot/aubo_driver/CMakeFiles/aubo_gazebo_driver.dir/src/aubo_gazebo_driver.cpp.o
[  6%] Linking CXX executable /home/rase/catkin_ws/devel/lib/aubo_driver/aubo_gazebo_driver
[  6%] Built target aubo_gazebo_driver
Scanning dependencies of target aubo_i5_kinematic
[  7%] Building CXX object aubo_robot/aubo_kinematics/CMakeFiles/aubo_i5_kinematic.dir/src/kinematics.cpp.o
[  8%] Linking CXX shared library /home/rase/catkin_ws/devel/lib/libaubo_i5_kinematic.so
[  8%] Built target aubo_i5_kinematic
Scanning dependencies of target aubo_i10_kinematic
[  9%] Building CXX object aubo_robot/aubo_kinematics/CMakeFiles/aubo_i10_kinematic.dir/src/kinematics.cpp.o
[ 10%] Linking CXX shared library /home/rase/catkin_ws/devel/lib/libaubo_i10_kinematic.so
[ 10%] Built target aubo_i10_kinematic
Scanning dependencies of target aubo_i3_kinematic
[ 12%] Building CXX object aubo_robot/aubo_kinematics/CMakeFiles/aubo_i3_kinematic.dir/src/kinematics.cpp.o
[ 13%] Linking CXX executable /home/rase/catkin_ws/devel/lib/aubo_demo/Test_Aubokinematic
[ 14%] Linking CXX executable /home/rase/catkin_ws/devel/lib/aubo_demo/MoveGroupInterface_To_Kinetic
[ 15%] Linking CXX executable /home/rase/catkin_ws/devel/lib/aubo_demo/AuboTest_kinetic
[ 15%] Built target Test_Aubokinematic
Scanning dependencies of target aubo_i5_moveit_kinematic_plugin
[ 16%] Building CXX object aubo_robot/aubo_kinematics/CMakeFiles/aubo_i5_moveit_kinematic_plugin.dir/src/aubo_moveit_plugin.cpp.o
[ 16%] Built target MoveGroupInterface_To_Kinetic
[ 16%] Built target AuboTest_kinetic
Scanning dependencies of target aubo_i10_moveit_kinematic_plugin
Scanning dependencies of target aubo_joint_trajectory_action
[ 19%] Building CXX object aubo_robot/aubo_controller/CMakeFiles/aubo_joint_trajectory_action.dir/src/joint_trajectory_action.cpp.o
[ 19%] Building CXX object aubo_robot/aubo_kinematics/CMakeFiles/aubo_i10_moveit_kinematic_plugin.dir/src/aubo_moveit_plugin.cpp.o
[ 20%] Linking CXX shared library /home/rase/catkin_ws/devel/lib/libaubo_i3_kinematic.so
[ 20%] Built target aubo_i3_kinematic
Scanning dependencies of target aubo_planner_test
[ 21%] Building CXX object aubo_robot/aubo_planner/CMakeFiles/aubo_planner_test.dir/src/aubo_planner_test.cpp.o
^[[B^[[B^[[D^[[D[ 22%] Linking CXX executable /home/rase/catkin_ws/devel/lib/aubo_controller/aubo_joint_trajectory_action
/usr/bin/ld: cannot find -lindustrial_robot_client
collect2: error: ld returned 1 exit status
aubo_robot/aubo_controller/CMakeFiles/aubo_joint_trajectory_action.dir/build.make:122: recipe for target '/home/rase/catkin_ws/devel/lib/aubo_controller/aubo_joint_trajectory_action' failed
make[2]: *** [/home/rase/catkin_ws/devel/lib/aubo_controller/aubo_joint_trajectory_action] Error 1
CMakeFiles/Makefile2:5788: recipe for target 'aubo_robot/aubo_controller/CMakeFiles/aubo_joint_trajectory_action.dir/all' failed
make[1]: *** [aubo_robot/aubo_controller/CMakeFiles/aubo_joint_trajectory_action.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
^Caubo_robot/aubo_kinematics/CMakeFiles/aubo_i5_moveit_kinematic_plugin.dir/build.make:62: recipe for target 'aubo_robot/aubo_kinematics/CMakeFiles/aubo_i5_moveit_kinematic_plugin.dir/src/aubo_moveit_plugin.cpp.o' failed
Traceback (most recent call last):
make[2]: *** [aubo_robot/aubo_kinematics/CMakeFiles/aubo_i5_moveit_kinematic_plugin.dir/src/aubo_moveit_plugin.cpp.o] Interrupt
  File "/opt/ros/kinetic/bin/catkin_make", line 306, in <module>
    sys.exit(main())
  File "/opt/ros/kinetic/bin/catkin_make", line 249, in main
    run_command(cmd, make_path)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/catkin/builder.py", line 241, in run_command
CMakeFiles/Makefile2:5686: recipe for target 'aubo_robot/aubo_kinematics/CMakeFiles/aubo_i5_moveit_kinematic_plugin.dir/all' failed
make[1]: *** [aubo_robot/aubo_kinematics/CMakeFiles/aubo_i5_moveit_kinematic_plugin.dir/all] Interrupt
aubo_robot/aubo_planner/CMakeFiles/aubo_planner_test.dir/build.make:62: recipe for target 'aubo_robot/aubo_planner/CMakeFiles/aubo_planner_test.dir/src/aubo_planner_test.cpp.o' failed
make[2]: *** [aubo_robot/aubo_planner/CMakeFiles/aubo_planner_test.dir/src/aubo_planner_test.cpp.o] Interrupt
CMakeFiles/Makefile2:6163: recipe for target 'aubo_robot/aubo_planner/CMakeFiles/aubo_planner_test.dir/all' failed
make[1]: *** [aubo_robot/aubo_planner/CMakeFiles/aubo_planner_test.dir/all] Interrupt
aubo_robot/aubo_kinematics/CMakeFiles/aubo_i10_moveit_kinematic_plugin.dir/build.make:62: recipe for target 'aubo_robot/aubo_kinematics/CMakeFiles/aubo_i10_moveit_kinematic_plugin.dir/src/aubo_moveit_plugin.cpp.o' failed
make[2]: *** [aubo_robot/aubo_kinematics/CMakeFiles/aubo_i10_moveit_kinematic_plugin.dir/src/aubo_moveit_plugin.cpp.o] Interrupt
CMakeFiles/Makefile2:5723: recipe for target 'aubo_robot/aubo_kinematics/CMakeFiles/aubo_i10_moveit_kinematic_plugin.dir/all' failed
make[1]: *** [aubo_robot/aubo_kinematics/CMakeFiles/aubo_i10_moveit_kinematic_plugin.dir/all] Interrupt
Makefile:138: recipe for target 'all' failed
make: *** [all] Interrupt
    proc.wait()
  File "/usr/lib/python2.7/subprocess.py", line 1392, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
rase@rase-VirtualBox:~/catkin_ws$ catkin_make
Base path: /home/rase/catkin_ws
Source space: /home/rase/catkin_ws/src
Build space: /home/rase/catkin_ws/build
Devel space: /home/rase/catkin_ws/devel
Install space: /home/rase/catkin_ws/install
####
####
####
####
[  2%] Built target MoveGroupInterface_To_Kinetic
[  4%] Built target Test_Aubokinematic
[  4%] Built target _aubo_msgs_generate_messages_check_deps_SetPayload
[  7%] Built target AuboTest_kinetic
[  7%] Built target std_msgs_generate_messages_nodejs
[  7%] Built target _aubo_msgs_generate_messages_check_deps_IOState
[  7%] Built target _aubo_msgs_generate_messages_check_deps_JointPos
[  7%] Built target _aubo_msgs_generate_messages_check_deps_GoalPoint
[  7%] Built target _aubo_msgs_generate_messages_check_deps_SetIO
[  7%] Built target _aubo_msgs_generate_messages_check_deps_Digital
[  7%] Built target _aubo_msgs_generate_messages_check_deps_Analog
[  7%] Built target _aubo_msgs_generate_messages_check_deps_TraPoint
[  7%] Built target std_msgs_generate_messages_py
[  7%] Built target _aubo_msgs_generate_messages_check_deps_GetFK
[  7%] Built target std_msgs_generate_messages_cpp
[  7%] Built target std_msgs_generate_messages_eus
[  7%] Built target _aubo_msgs_generate_messages_check_deps_GetIK
[  7%] Built target std_msgs_generate_messages_lisp
[  9%] Built target aubo_gazebo_driver
[ 12%] Built target aubo_i5_kinematic
[ 14%] Built target aubo_i10_kinematic
[ 16%] Built target aubo_i3_kinematic
Scanning dependencies of target aubo_msgs_generate_messages_nodejs
[ 18%] Linking CXX executable /home/rase/catkin_ws/devel/lib/aubo_controller/aubo_joint_trajectory_action
Scanning dependencies of target aubo_msgs_generate_messages_py
[ 19%] Generating Javascript code from aubo_msgs/Digital.msg
[ 20%] Building CXX object aubo_robot/aubo_planner/CMakeFiles/aubo_planner_test.dir/src/aubo_planner_test.cpp.o
[ 21%] Generating Python from MSG aubo_msgs/Digital
/usr/bin/ld: cannot find -lindustrial_robot_client
collect2: error: ld returned 1 exit status
aubo_robot/aubo_controller/CMakeFiles/aubo_joint_trajectory_action.dir/build.make:122: recipe for target '/home/rase/catkin_ws/devel/lib/aubo_controller/aubo_joint_trajectory_action' failed
make[2]: *** [/home/rase/catkin_ws/devel/lib/aubo_controller/aubo_joint_trajectory_action] Error 1
CMakeFiles/Makefile2:5788: recipe for target 'aubo_robot/aubo_controller/CMakeFiles/aubo_joint_trajectory_action.dir/all' failed
make[1]: *** [aubo_robot/aubo_controller/CMakeFiles/aubo_joint_trajectory_action.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 22%] Generating Javascript code from aubo_msgs/Analog.msg
[ 24%] Generating Javascript code from aubo_msgs/IOState.msg
[ 25%] Generating Javascript code from aubo_msgs/TraPoint.msg
[ 26%] Generating Javascript code from aubo_msgs/JointPos.msg
[ 27%] Generating Python from MSG aubo_msgs/Analog
[ 28%] Generating Javascript code from aubo_msgs/GoalPoint.msg
[ 30%] Generating Javascript code from aubo_msgs/SetPayload.srv
[ 31%] Generating Javascript code from aubo_msgs/GetIK.srv
[ 32%] Generating Javascript code from aubo_msgs/SetIO.srv
[ 33%] Generating Javascript code from aubo_msgs/GetFK.srv
[ 34%] Generating Python from MSG aubo_msgs/IOState
[ 36%] Generating Python from MSG aubo_msgs/TraPoint
[ 36%] Built target aubo_msgs_generate_messages_nodejs
[ 37%] Generating Python from MSG aubo_msgs/JointPos
[ 38%] Generating Python from MSG aubo_msgs/GoalPoint
[ 39%] Generating Python code from SRV aubo_msgs/SetPayload
[ 40%] Generating Python code from SRV aubo_msgs/GetIK
[ 42%] Generating Python code from SRV aubo_msgs/SetIO
[ 43%] Generating Python code from SRV aubo_msgs/GetFK
[ 45%] Generating Python srv __init__.py for aubo_msgs
[ 45%] Generating Python msg __init__.py for aubo_msgs
[ 45%] Built target aubo_msgs_generate_messages_py
[ 46%] Linking CXX executable /home/rase/catkin_ws/devel/lib/aubo_planner/aubo_planner_test
[ 46%] Built target aubo_planner_test
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by Tathipan** [comment]
some one help me please
