### ISSUE TITLE
aubo_control does not build on indigo

### ISSUE THREAD

**Issue by tfoote** [auboliuxin/aubo_robot#4]
Example: http://build.ros.org/view/Ibin_arm_uThf/job/Ibin_uT64__aubo_control__ubuntu_trusty_amd64__binary/77/console

```
DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_PREFIX_PATH=/opt/ros/indigo
00:36:17 -- The C compiler identification is GNU 4.8.4
00:36:17 -- The CXX compiler identification is GNU 4.8.4
00:36:17 -- Check for working C compiler: /usr/bin/x86_64-linux-gnu-gcc
00:36:17 -- Check for working C compiler: /usr/bin/x86_64-linux-gnu-gcc -- works
00:36:17 -- Detecting C compiler ABI info
00:36:17 -- Detecting C compiler ABI info - done
00:36:17 -- Check for working CXX compiler: /usr/bin/x86_64-linux-gnu-g++
00:36:17 -- Check for working CXX compiler: /usr/bin/x86_64-linux-gnu-g++ -- works
00:36:17 -- Detecting CXX compiler ABI info
00:36:17 -- Detecting CXX compiler ABI info - done
00:36:17 -- Using CATKIN_DEVEL_PREFIX: /tmp/binarydeb/ros-indigo-aubo-control-0.3.12/obj-x86_64-linux-gnu/devel
00:36:17 -- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
00:36:17 -- This workspace overlays: /opt/ros/indigo
00:36:17 -- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
00:36:17 -- Using PYTHON_EXECUTABLE: /usr/bin/python
00:36:17 -- Using Debian Python package layout
00:36:17 -- Using empy: /usr/bin/empy
00:36:18 -- Using CATKIN_ENABLE_TESTING: ON
00:36:18 -- Skip enable_testing() when building binary package
00:36:18 -- Using CATKIN_TEST_RESULTS_DIR: /tmp/binarydeb/ros-indigo-aubo-control-0.3.12/obj-x86_64-linux-gnu/test_results
00:36:18 -- Looking for include file pthread.h
00:36:18 -- Looking for include file pthread.h - found
00:36:18 -- Looking for pthread_create
00:36:18 -- Looking for pthread_create - not found
00:36:18 -- Looking for pthread_create in pthreads
00:36:18 -- Looking for pthread_create in pthreads - not found
00:36:18 -- Looking for pthread_create in pthread
00:36:18 -- Looking for pthread_create in pthread - found
00:36:18 -- Found Threads: TRUE  
00:36:18 -- Found gtest sources under '/usr/src/gtest': gtests will be built
00:36:18 -- Using Python nosetests: /usr/bin/nosetests-2.7
00:36:18 -- catkin 0.6.18
00:36:19 -- Using these message generators: gencpp;genlisp;genpy
00:36:19 --  CMAKE_MODULE_PATH  /tmp/binarydeb/ros-indigo-aubo-control-0.3.12/cmake
00:36:19 -- Could NOT find libpcan headers.
00:36:19 -- Could NOT find libpcan library.
00:36:19 -- Found CommAPI include dir: /tmp/binarydeb/ros-indigo-aubo-control-0.3.12/include/comm
00:36:19 -- Found CommAPI library: /tmp/binarydeb/ros-indigo-aubo-control-0.3.12/lib/lib64/libI5-CAN.so
00:36:19 CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
00:36:19 Please set them or make sure they are set and tested correctly in the CMake files:
00:36:19 LIBPCAN_LIB
00:36:19     linked by target "joint_control_pcan" in directory /tmp/binarydeb/ros-indigo-aubo-control-0.3.12/src/joint_control_pcan
00:36:19 
00:36:19 -- Configuring incomplete, errors occurred!
00:36:19 See also "/tmp/binarydeb/ros-indigo-aubo-control-0.3.12/obj-x86_64-linux-gnu/CMakeFiles/CMakeOutput.log".
00:36:19 See also "/tmp/binarydeb/ros-indigo-aubo-control-0.3.12/obj-x86_64-linux-gnu/CMakeFiles/CMakeError.log".
00:36:19 dh_auto_configure: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_PREFIX_PATH=/opt/ros/indigo returned exit code 1
00:36:19 make[1]: *** [override_dh_auto_configure] Error 2
00:36:19 make[1]: Leaving directory `/tmp/binarydeb/ros-indigo-aubo-control-0.3.12'
00:36:19 make: *** [build] Error 2
00:36:19 dpkg-buildpackage: error: debian/rules build gave error exit status 2
00:36:19 E: Building failed
00:36:19 Traceback (most recent call last):
00:36:19   File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 133, in build_binarydeb
00:36:19     subprocess.check_call(cmd, cwd=source_dir)
00:36:19   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
00:36:19     raise CalledProcessError(retcode, cmd)
00:36:19 subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-indigo-aubo-control']' returned non-zero exit status 1
00:36:19 # END SUBSECTION
00:36:19 
00:36:19 --------------------------------------------------------------------------------------------------
00:36:19 `apt-src build ros-indigo-aubo-control` failed.
00:36:19 This is usually because of an error building the package.
00:36:19 The traceback from this failure (just above) is printed for completeness, but you can ignore it.
00:36:19 You should look above `E: Building failed` in the build log for the actual cause of the failure.
00:36:19 --------------------------------------------------------------------------------------------------
00:36:19 
```

**Comment by liuxinwust** [comment]
It need peak can drivers,you can install it,see:http://wiki.ros.org/aubo_robot/Tutorials/Getting%20Started%20with%20a%20Aubo%20Robot

**Comment by tfoote** [comment]
If you have an external dependency like that you cannot release the package onto the buildfarm successfully. I've removed it and aubo_robot which is dependent on aubo_control from the buildfarm. https://github.com/ros/rosdistro/pull/13322

**Comment by auboliuxin** [comment]
I roslaunch rviz success a few days ago,but now I do this there is a loaded error.I try all means,but not solve it .I don't know how to do.

my source file:
......
#include <pluginlib/class_list_macros.h>
PLUGINLIB_EXPORT_CLASS(aubo_panel::AuboPanel,rviz::Panel)

my CMakeList.txt:
......
# install moveit plugin description file
install(FILES aubo_rviz_plugins.xml
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
)
my package.xml:
....
<buildtool_depend>catkin</buildtool_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>aubo_msgs</build_depend>
  <build_depend>rviz</build_depend>
  <build_depend>pluginlib</build_depend>
  <build_depend>class_loader</build_depend>

  <run_depend>roscpp</run_depend>
  <run_depend>rospy</run_depend>
  <run_depend>std_msgs</run_depend>
  <run_depend>sensor_msgs</run_depend>
  <run_depend>aubo_msgs</run_depend>
  <run_depend>pluginlib</run_depend>
  <run_depend>rviz</run_depend>
  <run_depend>class_loader</run_depend>

  
  <export>
    <rviz plugin="${prefix}/aubo_rviz_plugins.xml"/>
  </export>


load error details:


The class required for this panel, 'aubo_panel/Teleop', could not be loaded.
Error:
Failed to load library /home/user/catkin_ws/devel/lib//libaubo_panel.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /home/user/catkin_ws/devel/lib//libaubo_panel.so: undefined symbol: _ZTVN10aubo_panel9AuboPanelE)

**Comment by auboliuxin** [comment]
I roslaunch rviz success a few days ago,but now I do this there is a loaded error.I try all means,but not solve it .I don't know how to do.

my source file:
......
#include <pluginlib/class_list_macros.h>
PLUGINLIB_EXPORT_CLASS(aubo_panel::AuboPanel,rviz::Panel)

my CMakeList.txt:
......
install(FILES aubo_rviz_plugins.xml
DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
)

my package.xml:
....
<buildtool_depend>catkin</buildtool_depend>
<build_depend>roscpp</build_depend>
<build_depend>rospy</build_depend>
<build_depend>std_msgs</build_depend>
<build_depend>sensor_msgs</build_depend>
<build_depend>aubo_msgs</build_depend>
<build_depend>rviz</build_depend>
<build_depend>pluginlib</build_depend>
<build_depend>class_loader</build_depend>

<run_depend>roscpp</run_depend>
<run_depend>rospy</run_depend>
<run_depend>std_msgs</run_depend>
<run_depend>sensor_msgs</run_depend>
<run_depend>aubo_msgs</run_depend>
<run_depend>pluginlib</run_depend>
<run_depend>rviz</run_depend>
<run_depend>class_loader</run_depend>

load error details:

The class required for this panel, 'aubo_panel/Teleop', could not be loaded.
Error:
Failed to load library /home/user/catkin_ws/devel/lib//libaubo_panel.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /home/user/catkin_ws/devel/lib//libaubo_panel.so: undefined symbol: _ZTVN10aubo_panel9AuboPanelE)

**Comment by auboliuxin** [comment]
I roslaunch rviz success a few days ago,but now I do this there is a loaded error.I try all means,but not solve it .I don't know how to do. Please help me,you can see more details code at aubo_panel.

my source file:
......
#include <pluginlib/class_list_macros.h>
PLUGINLIB_EXPORT_CLASS(aubo_panel::AuboPanel,rviz::Panel)

my CMakeList.txt:
......
install(FILES aubo_rviz_plugins.xml
DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
)

my package.xml:
....
<buildtool_depend>catkin</buildtool_depend>
<build_depend>roscpp</build_depend>
<build_depend>rospy</build_depend>
<build_depend>std_msgs</build_depend>
<build_depend>sensor_msgs</build_depend>
<build_depend>aubo_msgs</build_depend>
<build_depend>rviz</build_depend>
<build_depend>pluginlib</build_depend>
<build_depend>class_loader</build_depend>

<run_depend>roscpp</run_depend>
<run_depend>rospy</run_depend>
<run_depend>std_msgs</run_depend>
<run_depend>sensor_msgs</run_depend>
<run_depend>aubo_msgs</run_depend>
<run_depend>pluginlib</run_depend>
<run_depend>rviz</run_depend>
<run_depend>class_loader</run_depend>
<export>
   <rviz plugin="${prefix}/aubo_rviz_plugins.xml"/>
</export>

load error details:

The class required for this panel, 'aubo_panel/Teleop', could not be loaded.
Error:
Failed to load library /home/user/catkin_ws/devel/lib//libaubo_panel.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /home/user/catkin_ws/devel/lib//libaubo_panel.so: undefined symbol: _ZTVN10aubo_panel9AuboPanelE)

**Comment by auboliuxin** [comment]
I roslaunch rviz success a few days ago,but now I do this there is a loaded error.I try all means,but not solve it .I don't know how to do. Please help me,you can see more details code at aubo_panel.

my source file:
......
#include <pluginlib/class_list_macros.h>
PLUGINLIB_EXPORT_CLASS(aubo_panel::AuboPanel,rviz::Panel)

my CMakeList.txt:
......
install(FILES aubo_rviz_plugins.xml
DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
)

my package.xml:
....
<buildtool_depend>catkin</buildtool_depend>
<build_depend>roscpp</build_depend>
<build_depend>rospy</build_depend>
<build_depend>std_msgs</build_depend>
<build_depend>sensor_msgs</build_depend>
<build_depend>aubo_msgs</build_depend>
<build_depend>rviz</build_depend>
<build_depend>pluginlib</build_depend>
<build_depend>class_loader</build_depend>

<run_depend>roscpp</run_depend>
<run_depend>rospy</run_depend>
<run_depend>std_msgs</run_depend>
<run_depend>sensor_msgs</run_depend>
<run_depend>aubo_msgs</run_depend>
<run_depend>pluginlib</run_depend>
<run_depend>rviz</run_depend>
<run_depend>class_loader</run_depend>
<export>
    <rviz plugin="${prefix}/aubo_rviz_plugins.xml"/>
  </export>

load error details:

The class required for this panel, 'aubo_panel/Teleop', could not be loaded.
Error:
Failed to load library /home/user/catkin_ws/devel/lib//libaubo_panel.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /home/user/catkin_ws/devel/lib//libaubo_panel.so: undefined symbol: _ZTVN10aubo_panel9AuboPanelE)

**Comment by auboliuxin** [comment]
I roslaunch rviz success a few days ago,but now I do this there is a loaded error.I try all means,but not solve it .I don't know how to do. Please help me,you can see more details code at aubo_panel.

my source file:
......
#include <pluginlib/class_list_macros.h>
PLUGINLIB_EXPORT_CLASS(aubo_panel::AuboPanel,rviz::Panel)
******************************************************************
my CMakeList.txt:
......
install(FILES aubo_rviz_plugins.xml
DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
)
********************************************************
my package.xml:
....
<buildtool_depend>catkin</buildtool_depend>
<build_depend>roscpp</build_depend>
<build_depend>rospy</build_depend>
<build_depend>std_msgs</build_depend>
<build_depend>sensor_msgs</build_depend>
<build_depend>aubo_msgs</build_depend>
<build_depend>rviz</build_depend>
<build_depend>pluginlib</build_depend>
<build_depend>class_loader</build_depend>

<run_depend>roscpp</run_depend>
<run_depend>rospy</run_depend>
<run_depend>std_msgs</run_depend>
<run_depend>sensor_msgs</run_depend>
<run_depend>aubo_msgs</run_depend>
<run_depend>pluginlib</run_depend>
<run_depend>rviz</run_depend>
<run_depend>class_loader</run_depend>
<export>
    <rviz plugin="${prefix}/aubo_rviz_plugins.xml"/>
  </export>
******************************************************************
load error details:
The class required for this panel, 'aubo_panel/Teleop', could not be loaded.
Error:
Failed to load library /home/user/catkin_ws/devel/lib//libaubo_panel.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /home/user/catkin_ws/devel/lib//libaubo_panel.so: undefined symbol: _ZTVN10aubo_panel9AuboPanelE)

**Comment by auboliuxin** [comment]
I roslaunch rviz success a few days ago,but now I do this there is a loaded error.I try all means,but not solve it .I don't know how to do. Please help me,you can see more details code at aubo_panel.
why rviz load aubopanel successful a few days ago ,but now fail.


load error details:
The class required for this panel, 'aubo_panel/Teleop', could not be loaded.
Error:
Failed to load library /home/user/catkin_ws/devel/lib//libaubo_panel.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /home/user/catkin_ws/devel/lib//libaubo_panel.so: undefined symbol: _ZTVN10aubo_panel9AuboPanelE)

**Comment by auboliuxin** [comment]
I roslaunch rviz success a few days ago,but now I do this there is a loaded error.I try all means,but not solve it .I don't know how to do. Please help me,you can see more details code at aubo_panel.
why rviz load aubopanel successful a few days ago ,but now fail.   "Failed to load library /home/user/catkin_ws/devel/lib//libaubo_panel.so" why there is extral '/' in lib path. 

load error details:
The class required for this panel, 'aubo_panel/Teleop', could not be loaded.
Error:
Failed to load library /home/user/catkin_ws/devel/lib//libaubo_panel.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /home/user/catkin_ws/devel/lib//libaubo_panel.so: undefined symbol: _ZTVN10aubo_panel9AuboPanelE)
